[program:automation-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/automation-project/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/automation-queue-default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600

[program:automation-queue-webhooks]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/automation-project/artisan queue:work database --sleep=1 --tries=3 --max-time=3600 --queue=webhooks
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/log/supervisor/automation-queue-webhooks.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600

[group:automation-workers]
programs=automation-queue-default,automation-queue-webhooks
